// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnippetManagerData.Data;

namespace SnippetManagerData.Migrations
{
    [DbContext(typeof(SnippetDbContext))]
    partial class SnippetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("SnippetManagerData.Models.EnvironmentModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("SnippetManagerData.Models.OSModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("OperatingSystems");
                });

            modelBuilder.Entity("SnippetManagerData.Models.SnippetModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Environmentid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperatingSystemid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserID")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Environmentid");

                    b.HasIndex("OperatingSystemid");

                    b.ToTable("Snippets");
                });

            modelBuilder.Entity("SnippetManagerData.Models.SnippetModel", b =>
                {
                    b.HasOne("SnippetManagerData.Models.EnvironmentModel", "Environment")
                        .WithMany()
                        .HasForeignKey("Environmentid");

                    b.HasOne("SnippetManagerData.Models.OSModel", "OperatingSystem")
                        .WithMany()
                        .HasForeignKey("OperatingSystemid");

                    b.Navigation("Environment");

                    b.Navigation("OperatingSystem");
                });
#pragma warning restore 612, 618
        }
    }
}
